location: '/g/data/u46/users/dxr251/2nd-order-v1'

output_products:

  - name: cosine
    statistic: external
    file_path_template: 'cosine_{x}_{y}.tif'
    statistic_args:
        impl: model.CosineDistanceMAD
        num_threads: 3
    output_params:
      zlib: True
      fletcher32: True

  - name: euclidean
    statistic: external
    file_path_template: 'euclidean_{x}_{y}.tif'
    statistic_args:
        impl: model.EuclideanDistanceMAD
        num_threads: 3
    output_params:
      zlib: True
      fletcher32: True

  - name: braycurtis
    statistic: external
    file_path_template: 'braycurtis_{x}_{y}.tif'
    statistic_args:
        impl: model.BrayCurtisDistanceMAD
        num_threads: 3
    output_params:
      zlib: True
      fletcher32: True

  - name: ternary
    statistic: external
    file_path_template: 'ternary_{x}_{y}.tif'
    statistic_args:
        impl: model.TernaryMAD
        num_threads: 3
    output_params:
      zlib: True
      fletcher32: True

sources:

#  - product: ls5_nbart_albers
#    measurements: [blue, green, red, nir, swir1, swir2]
#    group_by: solar_day
#    masks:
#      - product: ls5_pq_albers
#        measurement: pixelquality
#        group_by: solar_day
#        fuse_func: datacube.helpers.ga_pq_fuser
#        flags:
#          contiguous: True
#          cloud_acca: no_cloud
#          cloud_fmask: no_cloud
#          cloud_shadow_acca: no_cloud_shadow
#          cloud_shadow_fmask: no_cloud_shadow
#          blue_saturated: False
#          green_saturated: False
#          red_saturated: False
#          nir_saturated: False
#          swir1_saturated: False
#          swir2_saturated: False
#
#  - product: ls7_nbart_albers
#    measurements: [blue, green, red, nir, swir1, swir2]
#    group_by: solar_day
#    masks:
#      - product: ls7_pq_albers
#        measurement: pixelquality
#        group_by: solar_day
#        fuse_func: datacube.helpers.ga_pq_fuser
#        flags:
#          contiguous: True
#          cloud_acca: no_cloud
#          cloud_fmask: no_cloud
#          cloud_shadow_acca: no_cloud_shadow
#          cloud_shadow_fmask: no_cloud_shadow
#          blue_saturated: False
#          green_saturated: False
#          red_saturated: False
#          nir_saturated: False
#          swir1_saturated: False
#          swir2_saturated: False

  - product: ls8_nbart_albers
    measurements: [blue, green, red, nir, swir1, swir2]
    group_by: solar_day
    masks:
      - product: ls8_pq_albers
        measurement: pixelquality
        group_by: solar_day
        fuse_func: datacube.helpers.ga_pq_fuser
        flags:
          contiguous: True
          cloud_acca: no_cloud
          cloud_fmask: no_cloud
          cloud_shadow_acca: no_cloud_shadow
          cloud_shadow_fmask: no_cloud_shadow
          blue_saturated: False
          green_saturated: False
          red_saturated: False
          nir_saturated: False
          swir1_saturated: False
          swir2_saturated: False

date_ranges:
  start_date: 2000-01-01
  end_date: 2020-01-01

storage:
  driver: GeoTiff

  crs: EPSG:3577
  tile_size:
    x: 25000.0
    y: 25000.0
  resolution:
    x: 25
    y: -25
  chunking:
    x: 256
    y: 256
    time: 1
  dimension_order: [time, y, x]

computation:
  chunking:
    x: 1000
    y: 200
