location: '/g/data/u46/users/dxr251/mad-annual'

output_products:

  - name: ternary
    statistic: external
    file_path_template: 'mad-{epoch_start:%Y%m%d}-{epoch_end:%Y%m%d}_{x}_{y}.tif'
    statistic_args:
        impl: model.TernaryMAD
        num_threads: 3
    output_params:
      zlib: True
      fletcher32: True

sources:

  - product: ls5_nbart_albers
    measurements: [blue, green, red, nir, swir1, swir2]
    group_by: solar_day
    masks:
      - product: ls5_pq_albers
        measurement: pixelquality
        group_by: solar_day
        fuse_func: datacube.helpers.ga_pq_fuser
        flags:
          contiguous: True
          cloud_acca: no_cloud
          cloud_fmask: no_cloud
          cloud_shadow_acca: no_cloud_shadow
          cloud_shadow_fmask: no_cloud_shadow
          blue_saturated: False
          green_saturated: False
          red_saturated: False
          nir_saturated: False
          swir1_saturated: False
          swir2_saturated: False

  - product: ls7_nbart_albers
    measurements: [blue, green, red, nir, swir1, swir2]
    group_by: solar_day
    masks:
      - product: ls7_pq_albers
        measurement: pixelquality
        group_by: solar_day
        fuse_func: datacube.helpers.ga_pq_fuser
        flags:
          contiguous: True
          cloud_acca: no_cloud
          cloud_fmask: no_cloud
          cloud_shadow_acca: no_cloud_shadow
          cloud_shadow_fmask: no_cloud_shadow
          blue_saturated: False
          green_saturated: False
          red_saturated: False
          nir_saturated: False
          swir1_saturated: False
          swir2_saturated: False

  - product: ls8_nbart_albers
    measurements: [blue, green, red, nir, swir1, swir2]
    group_by: solar_day
    masks:
      - product: ls8_pq_albers
        measurement: pixelquality
        group_by: solar_day
        fuse_func: datacube.helpers.ga_pq_fuser
        flags:
          contiguous: True
          cloud_fmask: no_cloud
          blue_saturated: False
          green_saturated: False
          red_saturated: False
          nir_saturated: False
          swir1_saturated: False
          swir2_saturated: False

date_ranges:
  start_date: 1980-01-01
  end_date: 2020-01-01
  stats_duration: 1y
  step_size: 1y

storage:
  driver: GeoTIFF
  crs: EPSG:3577
  tile_size:
    x: 100000.0
    y: 100000.0
  resolution:
    x: 25
    y: -25
  chunking:
    x: 256
    y: 256
    time: 1
  dimension_order: [time, y, x]

computation:
  chunking:
    x: 1000
    y: 200
